

use_frameworks!
platform :ios, '12.0'

target 'HLUIKit_Example' do
  pod 'HLUIKit', :path => '../'
  pod 'HLUIKit_Moya', :path => '../HLUIKit_Moya.podspec'
  pod 'HLUIKit_Bluetooth', :path => '../HLUIKit_Bluetooth.podspec'
  pod 'HLUIKit_Realm', :path => '../HLUIKit_Realm.podspec'
  pod 'RxBluetoothKit', :git => 'https://github.com/i-mobility/RxBluetoothKit.git', :tag => '7.0.2'

  target 'HLUIKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
