use_frameworks!
platform :ios, '10.0'

target 'HLUIKit_Example' do
  pod 'HLUIKit', :path => '../'

  target 'HLUIKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
